**NumPy Arrays**

In [9]:
my_list = [1,2,3]

In [10]:
import numpy as np

In [13]:
arr = np.array(my_list)

In [19]:
arr

array([1, 2, 3])

In [20]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [22]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
arr = np.arange(25)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
ranarr = np.random.randint(0,50,10)

In [52]:
ranarr

array([19,  6, 26, 20, 47,  0, 41, 15, 44, 31])

In [53]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
ranarr.max()

47

In [56]:
ranarr.min()

0

In [57]:
ranarr

array([19,  6, 26, 20, 47,  0, 41, 15, 44, 31])

In [60]:
ranarr.argmax()

4

In [61]:
arr = arr.reshape(5,5)

In [62]:
arr.shape

(5, 5)

In [63]:
arr.dtype

dtype('int32')

In [64]:
from numpy.random import randint

In [65]:
randint(2,10)

4